// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7NBb75DCd7pt0eq-TL9sihZijpljKkI',
    appId: '1:340672372687:web:4645aa844d2f533c3bfcba',
    messagingSenderId: '340672372687',
    projectId: 'foodly-firebase-db709',
    authDomain: 'foodly-firebase-db709.firebaseapp.com',
    storageBucket: 'foodly-firebase-db709.appspot.com',
    measurementId: 'G-Z3TRHNYG36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDMHr9pj8wgqMljZlDA4ili31h0frcDY',
    appId: '1:340672372687:android:1ef33420730ee7113bfcba',
    messagingSenderId: '340672372687',
    projectId: 'foodly-firebase-db709',
    storageBucket: 'foodly-firebase-db709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdnEMq73rpLxdC-XUaQVJ2gUwSe_C9l0',
    appId: '1:340672372687:ios:93a4d1b342c6f0e03bfcba',
    messagingSenderId: '340672372687',
    projectId: 'foodly-firebase-db709',
    storageBucket: 'foodly-firebase-db709.appspot.com',
    iosBundleId: 'com.example.foodlyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMdnEMq73rpLxdC-XUaQVJ2gUwSe_C9l0',
    appId: '1:340672372687:ios:7d5b6c6d882960643bfcba',
    messagingSenderId: '340672372687',
    projectId: 'foodly-firebase-db709',
    storageBucket: 'foodly-firebase-db709.appspot.com',
    iosBundleId: 'com.example.foodlyFirebase.RunnerTests',
  );
}
