// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzQ8F1Hd3a95wPuvH9wMK4X2E7cVqD_8',
    appId: '1:818688899000:web:a43ef87facb3320075414d',
    messagingSenderId: '818688899000',
    projectId: 'foodie-app-b6f8c',
    authDomain: 'foodie-app-b6f8c.firebaseapp.com',
    databaseURL: 'https://foodie-app-b6f8c-default-rtdb.firebaseio.com',
    storageBucket: 'foodie-app-b6f8c.appspot.com',
    measurementId: 'G-T1DGKN0Q6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLehHwjeaNc2zwKvC9sUmnQd-nx4ciXs',
    appId: '1:818688899000:android:046a747fc8c400aa75414d',
    messagingSenderId: '818688899000',
    projectId: 'foodie-app-b6f8c',
    databaseURL: 'https://foodie-app-b6f8c-default-rtdb.firebaseio.com',
    storageBucket: 'foodie-app-b6f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFIFJUbnqhfj8cG9l8VqcH21ZHAvxugI',
    appId: '1:818688899000:ios:97aea39ff59f5d7675414d',
    messagingSenderId: '818688899000',
    projectId: 'foodie-app-b6f8c',
    databaseURL: 'https://foodie-app-b6f8c-default-rtdb.firebaseio.com',
    storageBucket: 'foodie-app-b6f8c.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFIFJUbnqhfj8cG9l8VqcH21ZHAvxugI',
    appId: '1:818688899000:ios:ae7bfcf55294f89975414d',
    messagingSenderId: '818688899000',
    projectId: 'foodie-app-b6f8c',
    databaseURL: 'https://foodie-app-b6f8c-default-rtdb.firebaseio.com',
    storageBucket: 'foodie-app-b6f8c.appspot.com',
    iosBundleId: 'com.example.foodie.RunnerTests',
  );
}
